"""Add Activate to Reward, make type Unique

Revision ID: acdab5c8beb5
Revises: 81bd1c954cce
Create Date: 2025-04-07 22:51:15.269489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acdab5c8beb5'
down_revision: Union[str, None] = '81bd1c954cce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rewards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint("type_unique", ['type'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rewards', schema=None) as batch_op:
        batch_op.drop_constraint("type_unique", type_='unique')
        batch_op.drop_column('active')

    # ### end Alembic commands ###
