"""Change twitch reward id field name

Revision ID: f62920a6b4ec
Revises: 400c53a3ef80
Create Date: 2025-04-21 14:51:39.359500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f62920a6b4ec'
down_revision: Union[str, None] = '400c53a3ef80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rewards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('twitch_reward_id', sa.String(), nullable=True))
        batch_op.drop_constraint('reward_id_unique_constraint', type_='unique')
        batch_op.create_unique_constraint("reward_id_unique_constraint", ['twitch_reward_id'])
        batch_op.drop_column('reward_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rewards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reward_id', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint("reward_id_unique_constraint", type_='unique')
        batch_op.create_unique_constraint('reward_id_unique_constraint', ['reward_id'])
        batch_op.drop_column('twitch_reward_id')

    # ### end Alembic commands ###
